let orderSequence = 1;

const CANCELLATION_POLICY = "Free cancellation 7 days or more before service date; 10% of total order amount charged within 7 days.";

function nextOrderId(dateText = "") {
  const compactDate = (dateText || "20260601").replaceAll("-", "");
  const sequence = String(orderSequence).padStart(4, "0");
  orderSequence += 1;
  return `JTDOS-${compactDate}-${sequence}`;
}

function mapOrderStatus(quote) {
  return quote.operator_review_required ? "pending_operator_review" : "booking_request_created";
}

function createBookingRequest({ draftOrder, quote, customer = {} }) {
  const priceJpy = Number(quote.price_jpy || 0);
  const operatorReviewRequired = Boolean(quote.operator_review_required || draftOrder.operator_review_required);
  const orderId = draftOrder.order_id || nextOrderId(draftOrder.pickup_date);

  return {
    jtdos_order_id: orderId,
    source: "jtdos_ai_agent",
    source_channel: "ai_booking",
    service_type: draftOrder.service_type,
    region: draftOrder.region,
    status: mapOrderStatus({ operator_review_required: operatorReviewRequired }),
    order_status: mapOrderStatus({ operator_review_required: operatorReviewRequired }),
    driver_assignment_confirmed: false,
    vehicle_assignment_required: true,
    route: {
      pickup_location: draftOrder.pickup_location || draftOrder.arrival_airport,
      pickup_location_code: draftOrder.arrival_airport,
      dropoff_location: draftOrder.dropoff_location,
      arrival_airport: draftOrder.arrival_airport,
      departure_airport: "",
      flight_number: draftOrder.flight_number,
      pickup_date: draftOrder.pickup_date,
      pickup_time: draftOrder.pickup_time,
      timezone: "Asia/Tokyo",
    },
    customer: {
      name: customer.name || "Test Customer",
      country: customer.country || "United States",
      phone: customer.phone || "",
      email: customer.email || "",
      whatsapp: customer.whatsapp || "",
      line_contact: customer.line_contact || "",
      telegram: customer.telegram || "",
      preferred_language: draftOrder.preferred_language || customer.preferred_language || "English",
      primary_contact_channel: customer.primary_contact_channel || (customer.whatsapp ? "WhatsApp" : customer.email ? "Email" : "LINE"),
    },
    passenger: {
      passenger_count: draftOrder.passenger_count,
      luggage_count: draftOrder.luggage_count,
      ski_equipment_count: draftOrder.ski_equipment_count || 0,
      child_seat_required: draftOrder.child_seat_required || false,
      child_seat_count: draftOrder.child_seat_count || 0,
    },
    vehicle: {
      vehicle_type: quote.recommended_vehicle || draftOrder.recommended_vehicle || draftOrder.vehicle_type,
      vehicle_model_preference: "",
      luxury_vehicle_required: false,
      multiple_vehicles_required: false,
      vehicle_count: 1,
    },
    pricing: {
      currency: "JPY",
      price_jpy: priceJpy,
      price_usd_reference: quote.price_usd_reference,
      price_status: quote.price_status,
      quote_confidence: quote.quote_confidence,
      deposit_required: true,
      deposit_rate: 0.2,
      deposit_amount_jpy: Math.round(priceJpy * 0.2),
      paypal_payment_required: true,
      cancellation_policy: CANCELLATION_POLICY,
      final_confirmation_required_by_operator: operatorReviewRequired,
      included: quote.included,
      excluded: quote.excluded,
      breakdown: quote.breakdown,
    },
    charter: {
      charter_days: 0,
      charter_hours_per_day: 0,
      start_date: "",
      end_date: "",
      itinerary_text: "",
    },
    special_requests: {
      signage_required: draftOrder.signage_required || false,
      driver_language_required: draftOrder.preferred_language,
      notes_from_customer: draftOrder.notes_from_customer || "",
      internal_notes: "Generated by JTDOS AI Agent. This is a booking request, not final driver assignment.",
    },
    notification: {
      send_to_email: true,
      send_to_whatsapp: true,
      send_to_telegram: true,
    },
    metadata: {
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      created_by: "jtdos_ai_agent",
      operator_review_required: operatorReviewRequired,
      final_confirmation_required_by_operator: operatorReviewRequired,
      fixed_price_does_not_confirm_driver: true,
    },
  };
}

module.exports = {
  createBookingRequest,
  CANCELLATION_POLICY,
};
